### ISSUE TITLE
documentation request: initial state of instruction pointer

### ISSUE THREAD

**Issue by bjmgeek** [catseye/Nhohnhehr#1]
Please update the documentation to indicate the initial state (position and direction) of the Instruction Pointer.

thanks!

**Comment by cpressey** [comment]
@bjmgeek Is https://github.com/catseye/Nhohnhehr/blame/master/README.markdown#L59 not sufficient?

**Comment by bjmgeek** [comment]
Hah, I completely missed that, thanks!
